require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
      - 'db/**/*'
      - '.git/**/*'
      # - 'Gemfile'
      - 'console/*'
      - '_test_folder/*'

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
