# frozen_string_literal: true

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
      - 'db/**/*'
      - '.git/**/*'
      - 'console/*'
      - '_test_folder/*'
      - vendor/bundle/**/*

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Style/Documentation:
  Enabled: false