
version: 2.1

executors:
  default:
    working_directory: ~/repo
    description: The official CircleCI Ruby Docker image
    docker:
      - image: circleci/ruby:2.7.0

caches:
  - &bundle_cache_v1 v2-repo-{{ checksum 'Gemfile.lock' }}
  - &bundle_cache v2-repo-

commands:
  defaults:
    steps:
      - checkout
      - restore_cache:
          keys:
            - *bundle_cache_v1
            - *bundle_cache
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: *bundle_cache
          paths:
            - vendor/bundle

jobs:
  lintering:
    executor: default
    steps:
      - defaults

workflows:
  version: 2.1
  build:
    jobs: